name: thinky
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  google_fonts: ^6.2.1
  
  # Network
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Routing
  go_router: ^13.0.0
  logger: ^2.6.2
  
  # Environment
  flutter_dotenv: ^5.1.0
  
  # Audio Recording
  record: ^6.0.0
  path_provider: ^2.1.2
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/illustrations/
    - assets/backgrounds/
    - assets/auth/login/
    - assets/auth/register/
    - assets/auth/icons/
    - assets/auth/guest/
    - assets/welcome/
    - assets/welcome/page1/
    - assets/welcome/page2/
    - assets/missions/
    - assets/missions/animals/
    - assets/missions/color_circle/
    - assets/missions/draw_shapes/
    - assets/missions/geometric_shapes/
    - assets/missions/missions/
    - assets/missions/missions/presentation/
    - assets/missions/pixy_learns/
    - assets/missions/pixy_learns/images/
    - assets/missions/quiz/
    - assets/missions/group_sorting/
    - assets/missions/group_sorting/images/
    - assets/missions/group_sorting/images/fruits/
    - assets/missions/group_sorting/images/vegetables/
    - assets/missions/group_sorting/images/toys/
    - assets/missions/vocabulary/
    - assets/missions/describe_image/
    - assets/missions/pattern/
    - assets/missions/numbers/
    - assets/i18n/
    - assets/i18n/texts.json
    - assets/i18n/texts_ro.json
    - .env

